# Generated by Django 5.0.2 on 2024-02-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('project_name', models.CharField(max_length=100)),
                ('project_link', models.URLField(blank=True, max_length=500, verbose_name='Project link')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['id'],
            },
        ),
    ]
